spring:
  mail:
    host: smtp.163.com
    username: 18701781651@163.com
    port: 25
    protocol: smtp
    default-encoding: UTF-8
    password: chengz0709
    properties:
     smtp:
      auth: true